### ISSUE TITLE
Notify URL

### ISSUE THREAD

**Issue by nicolasricci** [ekyna/PayumMoneticoBundle#2]
@ekyna thanks for the bundle. I have a question regarding the notification URL. I have given to my bank the `payum_notify_do_unsafe` route (/payment/notify/unsafe/monetico). First of all could you please confirm this is the good one? I have the following error on the callback if this is the correct URL.

```
Uncaught PHP Exception Payum\Core\Exception\RequestNotSupportedException: "Request Notify{model: NULL} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker."
```

Not sure this is linked but I have bumped the composer.json with the following dependencies

```
"payum/payum-bundle": "^2.3",
"symfony/framework-bundle" : "~4.0",
```

I was waiting to make sure everything is working to push a PR.

Thanks for your help

**Comment by ekyna** [comment]
Hi @nicolasricci 
Can you please read my comment in PR #1 ?
Then tell me if you still have troubles implementing notify request/action.

**Comment by nicolasricci** [comment]
@ekyna you're a star. Thanks for the quick answer 👍 
I will submit a PR with SF4 compatibility if you are interested and you should definitely update the doc with this notify method.

**Comment by ekyna** [comment]
@nicolasricci You're welcome.
And yeah i really have to find some time to document all that stuff.
