### ISSUE TITLE
How to declare the Action?

### ISSUE THREAD

**Issue by Alexandre-T** [ekyna/PayumMoneticoBundle#3]
Thanks for your bundle! The CIC payment solution is a quite boring.

Since your last update, your bundle does no more handle convert request.

When I try to create a payment and forward user to the payum capture route, I handle this error :

> Request Convert is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

I understand the notify action, I had a similar notify action in a controller. But I'm not sure to understand why you drop the convert support. Could you explain it? 

I tried to create Action as [explained in documentation](https://github.com/ekyna/PayumMonetico/blob/master/src/Action/ConvertPaymentAction.php), but my Action was not found by Symfony. I found how to declare it with [Payum documentation](https://github.com/Payum/Payum/blob/master/docs/symfony/custom-action-usage.md)

And now I handle this error :
> The option "reference" with value "5da20326171c6" is invalid.

I know that the defined options are: "3dsdebrayable", "ThreeDSecureChallenge", "aliascb", "amount", "comment", "context", "currency", "date", "desactivemoyenpaiement", "email", "failure_url", "forcesaisiecb", "libelleMonetique", "locale", "protocole", "reference", "schedule", "success_url".

Looking into your Api source code, I found that reference is limited to 12 characters. Should I limit the 13characters number generated? I don't find any reference in CIC documentation.

Could you explain too why you have remove the convert support (I don't contest your choice :-) I would like to understand it) .

**Comment by ekyna** [comment]
Hi @Alexandre-T 

As monetico now requires you to provide billing information for 3DSecure v2 ([see this line](https://github.com/ekyna/PayumMonetico/blob/157049101f3f0e94f01ba79a487677198e58c440/src/Action/ConvertPaymentAction.php#L68)), this bundle can't include a working solution for the default payum payment model.

You need to create your own convert action and register it  as follow :
```xml
    <service id="AcmeBundle\Payum\Action\ConvertAction">
        <tag name="payum.action" factory="monetico" prepend="true"/>
    </service>
```
or
```yaml
    AcmeBundle\Payum\Action\ConvertAction:
        tags:
            - { name: 'payum.action', factory: 'monetico', prepend: true }
```
(Not sure that 'prepend' is needed)

**Comment by ekyna** [comment]
From Monetico documentation :

> 50 caractères alphanumériques maximum.
> Dans le cadre du protocole CB2A utilisé lors des demandes
> d’autorisation, seuls au plus 12 caractères alphanumériques seront
> transmis à l’acquéreur. Si la référence envoyée fait plus de 12
> caractères, Monetico Paiement génèrera une référence technique
> respectant ce critère.

[Page 8](https://www.monetico-paiement.fr/fr/info/documentations/Monetico_Paiement_documentation_technique_v2.1.pdf)

I guess i could allow for 50 max length reference, but i don't know what is CB2A protocol 😞

**Comment by Alexandre-T** [comment]
Thanks for your answers. 

I confirm that prepend is not necessary:

    App\Action\ConvertPaymentAction:
      public: true
      tags:
        - { name: payum.action, factory: monetico }

I think too that you could allow for 50 max length reference because of the last sentence in explanation.

I will fork your project to update documentation containing these explanations, before sending you a pull request. If you're agree, I can too replace 12 by 50 in the regexp.

**Comment by ekyna** [comment]
Ok for the reference max length change and doc improvement if you have time 🙂
